const OPENAI_MODEL = "gpt-4o";
const OPENAI_ROLE_SYSTEM = "system";
const OPENAI_ROLE_USER = "user";
const OPENAI_ROLE_ASSISTANT = "assistant";
const OPENAI_ERROR_BAD_REQUEST_ERROR = 400;
const OPENAI_ERROR_AUTHENTICATION_ERROR = 401;
const OPENAI_ERROR_PERMISSION_DENIED_ERROR = 403;
const OPENAI_ERROR_NOT_FOUND_ERROR = 404;
const OPENAI_ERROR_UNPROCESSABLE_ENTITY_ERROR = 422;
const OPENAI_ERROR_RATE_LIMIT_ERROR = 429;
const OPENAI_ERROR_INTERNAL_SERVER_ERROR = 500;

export {
  OPENAI_MODEL,
  OPENAI_ROLE_SYSTEM,
  OPENAI_ROLE_USER,
  OPENAI_ROLE_ASSISTANT,
  OPENAI_ERROR_BAD_REQUEST_ERROR,
  OPENAI_ERROR_AUTHENTICATION_ERROR,
  OPENAI_ERROR_PERMISSION_DENIED_ERROR,
  OPENAI_ERROR_NOT_FOUND_ERROR,
  OPENAI_ERROR_UNPROCESSABLE_ENTITY_ERROR,
  OPENAI_ERROR_RATE_LIMIT_ERROR,
  OPENAI_ERROR_INTERNAL_SERVER_ERROR,
};
